version: "3.8"

services:
  authenticator-service:
    build:
      target: production
    environment:
      CLIENT_SECRET: ${CLIENT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
    command: node build/index.js
