version: "3.8"

services:
  authenticator-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      CLIENT_SECRET: ${CLIENT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
    # create volumes to support hot reload
    volumes:
      - ./src:/code-overview-authenticator/src
      - ./nodemon.json:/code-overview-authenticator/nodemon.json
    container_name: authenticator-service
    ports:
      - "8000:8000"
    command: npm run start
